[package]
name = "eve-message-diagnostics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
eve-message-api = { path = "../message-api" }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
eve-control-api = { path = "../control-api" }
eve-session-api = { path = "../session-api" }
tokio.workspace = true
